spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/kouydong
    username: kouydong
    password: 1234
    drive-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 10           # Max Connection size 10개
      connection-timeout: 5000        # Connection Timeout 시간 5초
      connection-init-sql: SELECT 1   # Connection 초기 SQL
      validation-timeout: 2000        # 유효성 Timeout 시간 2초
      minimum-idle: 10
      idle-timeout: 600000
      max-lifetime: 1800000
  jpa:
    show_sql: true
    hibernate:
      dialect: org.hibernate.dialect.ProgressDialect
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true